// js/stores/defaultCharacter.js

DndSheet.stores.defaultCharacter = {
    name: 'Valerius',
    race: { name: '' },
    subrace: { name: '' },
    classes: [{ name: '', level: 1, subclassName: '' }],
    alignment: 'Lawful Good',
    size: 'Medium',
    experience: { current: 0, toNext: 300 },
    hp: 10,
    maxHp: 10,
    tempHp: 0,
    hpRolls: {},
    hpOverride: null,
    initiative: { base: 0, other: 0 },
    proficiencyBonus: 2,
    languages: ['Common'],
    abilityScores: {
        str: { base: 10, racial: 0, other: 0 },
        dex: { base: 10, racial: 0, other: 0 },
        con: { base: 10, racial: 0, other: 0 },
        int: { base: 10, racial: 0, other: 0 },
        wis: { base: 10, racial: 0, other: 0 },
        cha: { base: 10, racial: 0, other: 0 },
    },
    savingThrows: {
        str: { proficient: false }, dex: { proficient: false }, con: { proficient: false },
        int: { proficient: false }, wis: { proficient: false }, cha: { proficient: false },
    },
    skills: {
        acrobatics: { ability: 'dex', proficient: false, expertise: false },
        animalHandling: { ability: 'wis', proficient: false, expertise: false },
        arcana: { ability: 'int', proficient: false, expertise: false },
        athletics: { ability: 'str', proficient: false, expertise: false },
        deception: { ability: 'cha', proficient: false, expertise: false },
        history: { ability: 'int', proficient: false, expertise: false },
        insight: { ability: 'wis', proficient: false, expertise: false },
        intimidation: { ability: 'cha', proficient: false, expertise: false },
        investigation: { ability: 'int', proficient: false, expertise: false },
        medicine: { ability: 'wis', proficient: false, expertise: false },
        nature: { ability: 'int', proficient: false, expertise: false },
        perception: { ability: 'wis', proficient: false, expertise: false },
        performance: { ability: 'cha', proficient: false, expertise: false },
        persuasion: { ability: 'cha', proficient: false, expertise: false },
        religion: { ability: 'int', proficient: false, expertise: false },
        sleightOfHand: { ability: 'dex', proficient: false, expertise: false },
        stealth: { ability: 'dex', proficient: false, expertise: false },
        survival: { ability: 'wis', proficient: false, expertise: false },
    },
    inventory: { 
        items: {}, 
        currency: { cp: 0, sp: 0, gp: 0, pp: 0 }, 
        containers: {} 
    },
    feats: {},
    abilities: {},
    notes: { 
        character: {}, 
        npcs: {}, 
        campaign: { sessionLog: [] }, 
        combat: '' 
    },
    spellcasting: {
        castingStat: 'int',
        spellSlots: {},
        dcOverride: null,
        attackBonusOverride: null,
    },
    spells: {},
    activeTimers: [],
    equippedItems: {},
};